### ISSUE TITLE
Support for buckets

### ISSUE THREAD

**Issue by jirka-h** [philovivero/distribution#1]
Hello,

does "distribution" has support for "buckets"? In other words, can keys be grouped together by value?

Example: when reading input with values in range 0-255, is there a way to create a histogram like this?
cat /dev/urandom | od  -tu1 -w1 -An -v | head -10000 | histogram.py | cut -d: -f1
# NumSamples = 10000; Min = 0.00; Max = 255.00
# Mean = 126.874400; Variance = 5451.876425; SD = 73.836823; Median 127.000000
# each ∎ represents a count of 14
    0.0000 -    25.5000 [  1052]
   25.5000 -    51.0000 [   994]
   51.0000 -    76.5000 [   976]
   76.5000 -   102.0000 [   997]
  102.0000 -   127.5000 [   989]
  127.5000 -   153.0000 [  1075]
  153.0000 -   178.5000 [   965]
  178.5000 -   204.0000 [   982]
  204.0000 -   229.5000 [   986]
  229.5000 -   255.0000 [   984]

Thanks a lot!
Jirka

**Comment by sjackman** [comment]
Bucketing into some number of evenly spaced buckets (say twenty) between the min and max value would be good enough for me.

**Comment by philovivero** [comment]
I simply cannot translate your suggestions into precise code. Perhaps you could submit a pull request with an implementation of what you're suggesting?
