### ISSUE TITLE
perl/python true-up

### ISSUE THREAD

**Issue by tstearns** [philovivero/distribution#11]
Opening this to track fixing up inconsistencies between Perl and Python versions, but only insofar as such differences make it difficult to run tests, per #10 
1. Perl randomizes the sort order of dictionaries, which causes histogram ties to be ordered randomly, which is particularly meaningful if the tie happens at the boundary of how many items are displayed in a histogram, so that sometimes one key or the other will fit inside the histogram. This causes the "runTest" script to return random results between runs even on the same machine, since some of the input test files have ties.
2. Perl visually renders left-justified tables, whereas Python right-justifies. e.g. "   logline|  6|" vs. "logline    |6  |" -- not sure whether this really matters, but would be nice to make the tests independent of it.
3. The Perl script is more forgiving about command line syntax, e.g. it will accept "--h" or "-height" whereas Python will not, it only accepts "-h" or "--height". Again, this probably doesn't matter, the more important task is to make "runTests.sh" use syntax that works between both versions, as it currently uses some Perl-only option syntax.

Opened a branch (https://github.com/tstearns/distribution/tree/perl-python-trueup) to propose fixes, with item 1 above done, and the other two to follow, will open the branch merge as a PR for review when done, referencing this ticket.

**Comment by philovivero** [comment]
Beautiful. Thanks! I just merged a quick change to the Python version to left-justify the keys so the outputs will match as far as that goes. I couldn't think of a quick way to make ties sort similarly, but if I come up with something later today, I'll make that change.

**Comment by tstearns** [comment]
Cool! I just submitted a PR with two commits, one which adds the key itself as a sort field for breaking ties, and one commit which uses standardized command line option syntax in the test script so that it works with both Perl and Python. Let me know what you think; I'm particularly curious if you're aware of edge cases that would cause the extra sort field to break anything (e.g. I'm not sure how it behaves across exotic unicode character sets, but am not too concerned since the goal is mostly to make the ties deterministic, not necessarily intuitive in every locale).

**Comment by philovivero** [comment]
I've also changed my mind and right-justified the keys in Python/Perl both.

I also believe deterministic sorting is the only thing that matters here, not intuitive sorting.

Ties are currently edge-case enough to not worry about it. I'm willing to solve the sorting intuition problem later when someone has that problem, and then it'll probably be toggled with a commandline switch.

**Comment by philovivero** [comment]
Oh, and BTW, thanks for your work here. This is great stuff.

**Comment by philovivero** [comment]
Looks like the way I justify the count/% columns is different between the two as well. Pretty sure this is a simple fix, but I might not get to it for a few hours.

```$ cat README.md | ./distribution -t=word -s=small
Key|Ct (Pct)    Histogram
  0|120 (2.69%) -------------------------------------------o
  o|119 (2.67%) ------------------------------------------o
the|93 (2.08%)  ---------------------------------o
  2|82 (1.84%)  -----------------------------o
  1|79 (1.77%)  ----------------------------o
 of|58 (1.30%)  --------------------o
  3|53 (1.19%)  ------------------o
  a|43 (0.96%)  ---------------o
 to|40 (0.90%)  --------------o
  4|40 (0.90%)  --------------o
$ cat README.md | ./distribution.py -t=word -s=small
Key|Ct  (Pct)   Histogram
  0|120 (2.69%) -------------------------------------------o
  o|119 (2.67%) ------------------------------------------o
the| 93 (2.08%) ---------------------------------o
  2| 82 (1.84%) -----------------------------o
  1| 79 (1.77%) ----------------------------o
 of| 58 (1.30%) --------------------o
  3| 53 (1.19%) ------------------o
  a| 43 (0.96%) ---------------o
 to| 40 (0.90%) --------------o
  4| 40 (0.90%) --------------o
```

**Comment by tstearns** [comment]
Cool, in the meantime, I've been fiddling with testing tweaks using "diff -w" to try to avoid whitespace discrepancies:
https://github.com/tstearns/distribution/commit/b59d77106af0aefef731f513d143a8cdad9e962a

There are a few other visual diff problems I'm trying to hunt down with the above diffing technique, but I think this is progress.

**Comment by tstearns** [comment]
As of the recent merge of PRs #13 #14 #15 #17, I think this is all done! Perl and Python seem consistent to me.
